# Generated by Django 4.2.4 on 2023-10-17 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='First name')),
                ('last_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Last name')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Nickname')),
                ('phone', models.CharField(blank=True, max_length=256, null=True, unique=True, verbose_name='Phone number')),
                ('time_zone', models.CharField(blank=True, max_length=256, null=True, verbose_name='Time zone')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users/avatars/', verbose_name='Avatar')),
                ('in_calendaria', models.BooleanField(default=False, help_text='Status (default "No")', verbose_name='Active?')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('status', models.CharField(blank=True, max_length=800, null=True, verbose_name='Text status')),
                ('status_change_at', models.DateTimeField(blank=True, null=True, verbose_name='Status change date')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
                ('is_online', models.BooleanField(default=False, help_text='Status (default "No")', verbose_name='Online?')),
                ('last_online', models.DateTimeField(blank=True, null=True, verbose_name='Last online')),
                ('is_staff', models.BooleanField(default=False, help_text='Only for admin panel', verbose_name='Is staff?')),
                ('is_active', models.BooleanField(default=True, help_text='Status (default "Yes")', verbose_name='Is active?')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='UserRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blocked', models.BooleanField(default=False, help_text='Статус (по умолчанию "Нет")', verbose_name='Blocked?')),
                ('muted', models.BooleanField(default=False, help_text='Статус (по умолчанию "Нет")', verbose_name='Muted?')),
                ('autosave_media', models.BooleanField(default=True, help_text='Статус (по умолчанию "Да")', verbose_name='Autosave media?')),
                ('blocked_desc', models.CharField(blank=True, max_length=100, null=True, verbose_name='Blocked description')),
                ('related_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation', to=settings.AUTH_USER_MODEL, verbose_name='Related user')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who owns the relation')),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme', models.CharField(default='default', max_length=200, verbose_name='Theme')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who owns the settings')),
            ],
            options={
                'verbose_name': 'Setting',
                'verbose_name_plural': 'Settings',
            },
        ),
        migrations.CreateModel(
            name='Privacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_actions', models.CharField(choices=[('No One', 'No One'), ('My Contacts', 'My Contacts'), ('All', 'All')], default='All', max_length=15, verbose_name='Who can see my last actions')),
                ('profile_image', models.CharField(choices=[('No One', 'No One'), ('My Contacts', 'My Contacts'), ('All', 'All')], default='All', max_length=15, verbose_name='Who can see my profile image')),
                ('group_chat_invite', models.CharField(choices=[('No One', 'No One'), ('My Contacts', 'My Contacts'), ('All', 'All')], default='All', max_length=15, verbose_name='Who can invite me to group chats')),
                ('event_invite', models.CharField(choices=[('No One', 'No One'), ('My Contacts', 'My Contacts'), ('All', 'All')], default='All', max_length=15, verbose_name='Who can invite me to events')),
                ('my_events', models.CharField(choices=[('No One', 'No One'), ('My Contacts', 'My Contacts'), ('All', 'All')], default='All', max_length=15, verbose_name='Who can see my events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who owns the privacy settings')),
            ],
            options={
                'verbose_name': 'Настройка',
                'verbose_name_plural': 'Настройки',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('type', models.CharField(max_length=100, verbose_name='Type')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone number')),
                ('in_calendaria', models.BooleanField(default=False, help_text='Status (default "No")', verbose_name='Active?')),
                ('is_deleted', models.BooleanField(default=False, help_text='Status (default "No")', verbose_name='Deleted?')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User who owns the contact')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
