# Generated by Django 4.2.4 on 2023-11-09 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='Nickname'),
            preserve_default=False,
        ),
    ]
