# Generated by Django 4.2.4 on 2023-10-17 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attachment_type', models.CharField(choices=[('IMAGE', 'IMAGE'), ('VIDEO', 'VIDEO'), ('FILE', 'FILE')], default='IMAGE', max_length=15, verbose_name='Attachment type')),
                ('thumbnail', models.ImageField(blank=True, max_length=256, null=True, upload_to='event/attachments/', verbose_name='Thumbnail source image')),
                ('duration', models.FloatField(blank=True, null=True, verbose_name='Duration')),
                ('attachment', models.FileField(blank=True, max_length=256, null=True, upload_to='event/attachments/', verbose_name='Attachment')),
                ('width', models.IntegerField(blank=True, null=True, verbose_name='Width')),
                ('height', models.IntegerField(blank=True, null=True, verbose_name='Height')),
                ('size', models.IntegerField(blank=True, null=True, verbose_name='Size')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Attachment',
                'verbose_name_plural': 'Attachments',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('all_day', models.BooleanField(default=False, help_text='All day? (default "No")', verbose_name='All day?')),
                ('start_date_time', models.DateTimeField(null=True, verbose_name='Start date')),
                ('end_date_time', models.DateTimeField(null=True, verbose_name='End date')),
                ('notice_before', models.IntegerField(blank=True, null=True, verbose_name='Notice before')),
                ('chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Chat id')),
                ('type', models.CharField(choices=[('Work', 'Work'), ('Home', 'Home'), ('Default', 'Default'), ('Shared', 'Shared')], default='Default', max_length=30, verbose_name='Event type')),
                ('recurrence_rule', models.CharField(max_length=250, null=True, verbose_name='Recurrence rule')),
                ('description', models.TextField(blank=True, max_length=1000, null=True, verbose_name='Description')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='event/covers/', verbose_name='Cover image')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='Updated at')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Creator', 'Creator'), ('Admin', 'Admin'), ('Default', 'Default')], default='Default', max_length=15, verbose_name='Role')),
                ('status', models.CharField(choices=[('Waiting', 'Waiting'), ('Maybe', 'Maybe'), ('Left', 'Left'), ('Declined', 'Declined'), ('Accepted', 'Accepted'), ('Kicked', 'Kicked')], default='Waiting', max_length=15, verbose_name='Invite status')),
                ('remind', models.CharField(choices=[('0', '0'), ('15', '15'), ('30', '30'), ('60', '60'), ('1440', '1440')], default='0', max_length=4, verbose_name='Remind duration')),
                ('remind_at', models.DateTimeField(blank=True, null=True, verbose_name='Remind at')),
            ],
            options={
                'verbose_name': 'Invite',
                'verbose_name_plural': 'Invites',
            },
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=256, verbose_name='Url')),
                ('title', models.CharField(blank=True, max_length=256, null=True, verbose_name='Title')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
            ],
            options={
                'verbose_name': 'Link',
                'verbose_name_plural': 'Links',
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=256, null=True, verbose_name='Address')),
                ('lng', models.FloatField(verbose_name='Longitude')),
                ('lat', models.FloatField(verbose_name='Latitude')),
            ],
            options={
                'verbose_name': 'Location',
                'verbose_name_plural': 'Locations',
            },
        ),
    ]
