version: '3.9'

networks:
  backend:
    name: backend
    external: true

services:
  app:
    hostname: app
    build:
      context: .
    restart: always
    command:
      - /bin/sh
      - -c
      - ./entrypoint.sh
    environment:
      - DJANGO_SECRET_KEY=${DJANGO_SECRET_KEY}
      - DJANGO_ALLOWED_HOSTS=${DOMAIN}
    user: 'django:django'
    volumes:
      - media:/vol/media
    ports:
      - '8000:8000'
    expose:
      - '8000'
    depends_on:
      - db
    networks:
      - backend

  proxy:
    hostname: proxy
    build:
      context: ./docker/proxy
    restart: always
    depends_on:
      - app
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - certbot-web:/vol/www
      - proxy-dhparams:/vol/proxy
      - certbot-certs:/etc/letsencrypt
    environment:
      - DOMAIN=${DOMAIN}
    networks:
      - backend

  certbot:
    build:
      context: ./docker/certbot
    command: echo "Skipping..."
    environment:
      - DOMAIN=${DOMAIN}
      - EMAIL=${ACME_DEFAULT_EMAIL}
    volumes:
      - certbot-web:/vol/www
      - certbot-certs:/etc/letsencrypt/
    depends_on:
      - proxy
    networks:
      - backend

  db:
    hostname: db
    image: postgres
    container_name: calendaria-postgres
    restart: always
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Calendaria-123
      POSTGRES_DB: calendaria
      POSTGRES_INITDB_ARGS: '--encoding=UTF-8 --locale=en_US.UTF-8 -A md5'
    ports:
      - '5432:5432'
      - '5433:5433'
    networks:
      - backend

volumes:
  certbot-web:
  proxy-dhparams:
  certbot-certs:
  postgres-data:
  media:
