# Generated by Django 4.2.4 on 2023-10-17 05:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
        ('events', '0001_initial'),
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='locationmessageattachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_location_attachments', to='chat.message', verbose_name='Message which contains this attachment'),
        ),
        migrations.AddField(
            model_name='link',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Message which contains this link'),
        ),
        migrations.AddField(
            model_name='eventmessageattachment',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='deletedmessage',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.member', verbose_name='Пользователь который удалил сообщение'),
        ),
        migrations.AddField(
            model_name='deletedmessage',
            name='message',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.message', verbose_name='Сообщение которое удалили'),
        ),
        migrations.AddField(
            model_name='deletedchat',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chat', verbose_name='Chat'),
        ),
        migrations.AddField(
            model_name='deletedchat',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.member', verbose_name='Member'),
        ),
        migrations.AddField(
            model_name='contactmessageattachment',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.contact', verbose_name='Contact'),
        ),
        migrations.AddField(
            model_name='contactmessageattachment',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='chat',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Created by'),
        ),
        migrations.AddField(
            model_name='chat',
            name='event',
            field=models.ForeignKey(blank=True, help_text='For direct chat - null, for group chat - null, for event chat - event', null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event'),
        ),
        migrations.AddField(
            model_name='chat',
            name='last_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_last_message', to='chat.message', verbose_name='Last message'),
        ),
        migrations.AddField(
            model_name='chat',
            name='pinned_message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chat_pinned_message', to='chat.message', verbose_name='Pinned message'),
        ),
        migrations.AddField(
            model_name='attachment',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='message_attachments', to='chat.message', verbose_name='Message which contains this attachment'),
        ),
        migrations.AlterUniqueTogether(
            name='member',
            unique_together={('chat', 'user')},
        ),
    ]
