# Generated by Django 4.2.4 on 2023-08-22 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Countrycode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('dial_code', models.CharField(max_length=7, verbose_name='Код телефона')),
                ('code', models.CharField(max_length=4, verbose_name='Код страны')),
                ('flag', models.CharField(blank=True, max_length=100, null=True, verbose_name='Флаг')),
            ],
            options={
                'verbose_name': 'Телефонный код',
                'verbose_name_plural': 'Телефонные коды',
            },
        ),
        migrations.CreateModel(
            name='Timezone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('value', models.CharField(max_length=250, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Часовой пояс',
                'verbose_name_plural': 'Часовые пояса',
            },
        ),
    ]
