# Generated by Django 4.2.4 on 2023-11-02 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medicines', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='symptom',
            name='medicines',
        ),
        migrations.AddField(
            model_name='medicine',
            name='symptoms',
            field=models.ManyToManyField(related_name='medicines', to='medicines.symptom'),
        ),
    ]
