# Generated by Django 4.2.4 on 2023-10-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('Common', 'Common'), ('Event', 'Event'), ('Contact', 'Contact')], default='Common', max_length=30, verbose_name='Notification type')),
                ('is_read', models.BooleanField(default=False, verbose_name='Is read')),
                ('notification_title', models.CharField(max_length=200, verbose_name='Notification title')),
                ('text', models.CharField(max_length=200, verbose_name='Notification text')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Created at')),
                ('contact_id', models.IntegerField(blank=True, null=True, verbose_name='contact_id')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='events.event', verbose_name='Event')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
